default: &default
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username:
  password:
  timeout: 5000


development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
